//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrohisUploadLib.Communication.Youtube {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrohisUploadLib.Communication.Youtube.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://accounts.google.com/o/oauth2/token ähnelt.
        /// </summary>
        internal static string AuthCodeAddress {
            get {
                return ResourceManager.GetString("AuthCodeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die code={0}&amp;client_id={1}&amp;client_secret={2}&amp;redirect_uri=urn:ietf:wg:oauth:2.0:oob&amp;grant_type=authorization_code ähnelt.
        /// </summary>
        internal static string AuthCodeContent {
            get {
                return ResourceManager.GetString("AuthCodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die POST ähnelt.
        /// </summary>
        internal static string AuthCodeMethod {
            get {
                return ResourceManager.GetString("AuthCodeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorization: Bearer {0} ähnelt.
        /// </summary>
        internal static string AuthHeader {
            get {
                return ResourceManager.GetString("AuthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die client_id={0}&amp;client_secret={1}&amp;refresh_token={2}&amp;grant_type=refresh_token ähnelt.
        /// </summary>
        internal static string AuthRefreshContent {
            get {
                return ResourceManager.GetString("AuthRefreshContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://accounts.google.com/o/oauth2/auth?client_id={0}&amp;redirect_uri={1}&amp;scope={2}&amp;response_type={3}&amp;approval_prompt=force&amp;access_type=offline ähnelt.
        /// </summary>
        internal static string AuthRequestUrl {
            get {
                return ResourceManager.GetString("AuthRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die code ähnelt.
        /// </summary>
        internal static string AuthResponseType {
            get {
                return ResourceManager.GetString("AuthResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://accounts.google.com/o/oauth2/revoke?token={0} ähnelt.
        /// </summary>
        internal static string AuthRevokeAddress {
            get {
                return ResourceManager.GetString("AuthRevokeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die content-range: bytes */{0} ähnelt.
        /// </summary>
        internal static string CheckStatusContentRangeHeader {
            get {
                return ResourceManager.GetString("CheckStatusContentRangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 812042275170-db6cf7ujravcq2l7vhu7gb7oodgii3e4.apps.googleusercontent.com ähnelt.
        /// </summary>
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cKUCRQz0sE4UUmvUHW6qckbP ähnelt.
        /// </summary>
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die content-length: {0} ähnelt.
        /// </summary>
        internal static string ContentLengthHeader {
            get {
                return ResourceManager.GetString("ContentLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die content-type: {0} ähnelt.
        /// </summary>
        internal static string ContentTypeHeader {
            get {
                return ResourceManager.GetString("ContentTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die application/x-www-form-urlencoded ähnelt.
        /// </summary>
        internal static string FormContentType {
            get {
                return ResourceManager.GetString("FormContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.googleapis.com/youtube/v3/playlistItems?part=contentDetails&amp;maxResults=50&amp;playlistId={0}{1} ähnelt.
        /// </summary>
        internal static string GetPlaylistItemsUrl {
            get {
                return ResourceManager.GetString("GetPlaylistItemsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GET ähnelt.
        /// </summary>
        internal static string GetPlaylistMethod {
            get {
                return ResourceManager.GetString("GetPlaylistMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;pageToken={0} ähnelt.
        /// </summary>
        internal static string GetPlaylistTokenAddition {
            get {
                return ResourceManager.GetString("GetPlaylistTokenAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die application/json; charset=utf-8 ähnelt.
        /// </summary>
        internal static string JSONContentType {
            get {
                return ResourceManager.GetString("JSONContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://localhost ähnelt.
        /// </summary>
        internal static string RedirectUriAutoGet {
            get {
                return ResourceManager.GetString("RedirectUriAutoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die urn:ietf:wg:oauth:2.0:oob ähnelt.
        /// </summary>
        internal static string RedirectUriManuGet {
            get {
                return ResourceManager.GetString("RedirectUriManuGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content-Range: bytes {0}-{1}/{2} ähnelt.
        /// </summary>
        internal static string ResumeUploadContentRangeHeader {
            get {
                return ResourceManager.GetString("ResumeUploadContentRangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PUT ähnelt.
        /// </summary>
        internal static string UploadMethod {
            get {
                return ResourceManager.GetString("UploadMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.googleapis.com/auth/youtube.upload+https://www.googleapis.com/auth/youtube.readonly ähnelt.
        /// </summary>
        internal static string UploadScope {
            get {
                return ResourceManager.GetString("UploadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&amp;part=snippet,status,contentDetails ähnelt.
        /// </summary>
        internal static string UploadUrl {
            get {
                return ResourceManager.GetString("UploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die POST ähnelt.
        /// </summary>
        internal static string UpoadInitMethod {
            get {
                return ResourceManager.GetString("UpoadInitMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die video/* ähnelt.
        /// </summary>
        internal static string VideoContentType {
            get {
                return ResourceManager.GetString("VideoContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x-upload-content-length: {0} ähnelt.
        /// </summary>
        internal static string XUploadContentLengthHeader {
            get {
                return ResourceManager.GetString("XUploadContentLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x-upload-content-type: {0} ähnelt.
        /// </summary>
        internal static string XUploadContentTypeHeader {
            get {
                return ResourceManager.GetString("XUploadContentTypeHeader", resourceCulture);
            }
        }
    }
}
